### ISSUE TITLE
2 WARNING: > wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'. ; > falling back to ArrayBuffer instantiation

### ISSUE THREAD

**Issue by leonbakadorov** [GramThanos/falcon.js#1]
What is? 

> wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

> falling back to ArrayBuffer instantiation

**Comment by GramThanos** [comment]
The error indicate that the webserver served the webassembly code with an unexpected mime type, thus the browser decided not to compile it.

**Comment by leonbakadorov** [comment]
> The error indicate that the webserver served the webassembly code with an unexpected mime type, thus the browser decided not to compile it.

And what to do? I have a version of Falcon JS (by cyph) which only consists of 1 .js file, but only one key size is generated there and in uintArray format (it turns out to be a long size).

In your implementation, 2 files are used, one of which has the .wasm extension and strange warnings appear because of it. But there is an opportunity to choose the size (512 suits me).

Do you plan to implement this algorithm completely in JavaScript without .wasm?

How to get rid of the above warnings at the moment?

**Comment by GramThanos** [comment]
First of all, thes current version of this library doesn't implement the latest version of the official falcon library (I haven't checked if there are changes between the version I used and the final version of the NIST competition).

Back to your question. So... webassembly usually comes in 2 versions, 1 in wasn that is the real webassembly and one in JavaScript for backwards compatibility with older browsers or browsers not supporting webassembly. The difference between them is the speed, as the wasm version should be faster.

The warning is just letting you know that your browser is switching from the wasm version to the JavaScript, which is not a real problem. Depending on how you host the wasm you may be able to configure your webserver to send the correct MIME type for the wasm files, so that your browser accepts it. If you want to use only the JavaScript version just ignore the wasm files (I haven't checked how to skip it completely but since the wasm will not be available, it will turn to the JavaScript version automatically).

**Comment by leonbakadorov** [comment]
Managed to eliminate warnings by adding mime.type to the web server configuration. Using Apache as an example, add to the end of the mime.types file:

#added in file mime.types
applecation/wasm wasm
